name: "Build"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
      - docker
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Build 🔧
        id: build
        run: |
          nix-build -j 4 docker.nix --argstr tag latest -o docker-img
          export DOCKERIMG=$(readlink ./docker-img)
          echo "::set-output name=docker-img::${DOCKERIMG}"
      - name: Upload docker image tgz
        uses: actions/upload-artifact@v2
        with:
          name: docker-img
          retention-days: 1
          path: |
            ${{ steps.build.outputs.docker-img }}

  docker:
    needs: ci
    runs-on: ubuntu-latest
    env:
      DOCKERTAG: latest
    steps:
      - name: Download docker img
        uses: actions/download-artifact@v2
        with:
          name: docker-img
      - name: Build & Publish Docker image to Docker Hub
        run: |
          ls
          docker load -i *docker-image-*.tar.gz
          echo ${{ secrets.DOCKER_PASS }} | docker login -u sridca --password-stdin
          set -x
          docker push sridca/themottedashboard:latest
