name: "Scheduled run"
on:
  schedule:
  - cron: "0 * * * *"
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch data
      run: |
        # Cannot use Nix in a fast workflow; let's hope jq/wget is installed
        bash ./content/fetcher
    - name: Build HTML 🔧
      run: |
        cd ./content
        mkdir ./.output
        export TARGET=$(pwd)/.output
        mkdir -p ${TARGET}/
        cp *.json $TARGET
        docker run -v $PWD:/data sridca/themottedashboard TheMotteDashboard gen /data/.output
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
        cname: themotte.srid.ca